### ISSUE TITLE
ATM9 crashes

### ISSUE THREAD

**Issue by EnterFor** [Gilded-Games/Nitrogen#18]
https://gist.github.com/EnterFor/aecc1459db347cdb609c08795a3a5122

Hi, I'm playing ATM9 modpack on the server, I'm not sure if the problem is here, but I found characters about your mod appear

I am Chinese, I use Google Translate, I don't know if you can understand

**Comment by bconlon1** [comment]
Seems the server is stalling out from a tick taking to long from something in Nitrogen's code. I'll have to look into this when I have time.

**Comment by bconlon1** [comment]
@EnterFor add this to the mods folder:

https://output.circle-artifacts.com/output/job/92c27415-5941-460b-931f-2168381f231a/artifacts/0/~/project/build/libs/nitrogen_internals-1.20.1-0.2.0-neoforge.jar

Let me know if it works.

**Comment by EnterFor** [comment]
I've installed it. I'll keep you posted.
Does the client need to install it?

**Comment by bconlon1** [comment]
No.

**Comment by EnterFor** [comment]
There are no server crashes so far, but I want to test it a little longer.
