### ISSUE TITLE
Improvement: Re-enable json minifying to save space

### ISSUE THREAD

**Issue by mrjasonn** [Gilded-Games/Nitrogen#31]
It seems like in the `build.gradle` file it has been disabled, so just bringing it up if you would like to.

**Comment by bconlon1** [comment]
I think I disabled it because it was causing a build failure that I needed to fix, I have plans to look into working with the plugin again.

**Comment by mrjasonn** [comment]
> I think I disabled it because it was causing a build failure that I needed to fix, I have plans to look into working with the plugin again.

In  The-Aether-Team/The-Aether#2014 it doesn't use machete to minify json, I suggest seeing if that works properly or not.

**Comment by bconlon1** [comment]
Ah I had not realized that PR had changed it's methods, either way I have been planning to look at all of that stuff and just haven't gotten around to it because of higher priority tasks.

**Comment by rhysdh540** [comment]
if you want I can make another pr that does the same method as the main repository.
the main advantages of that are that it unzips and processes the jar in memory, so no temporary files are made, and also that it's 1 less dependency to... depend on.

I may look into making that logic into an actual plugin sometime in the not-so-near future given how many times I've had to copy and paste it around.

**Comment by bconlon1** [comment]
A plugin would probably be ideal for keeping code organized.
